import { Pathology, System } from './types';

export const MASTER_CATALOG: Pathology[] = [
    // Cardiovascular
    {
      id: 'cardio-1',
      name: 'Infarto Agudo de Miocardio',
      sistema: System.CARDIOVASCULAR,
      etimologia: 'Del latín "infartus" (rellenar, embutir) y "myocardium" (músculo del corazón). Necrosis del músculo cardíaco por isquemia.',
      definicionClinica: 'Necrosis de una porción del músculo cardíaco que se produce como resultado de la obstrucción del flujo sanguíneo en una de las arterias coronarias.',
      sintomatologia: ['Dolor torácico opresivo irradiado', 'Diaforesis', 'Náuseas y vómitos', 'Disnea', 'Ansiedad'],
      diagnosticoNANDA: '[00024] Perfusión tisular ineficaz (cardiopulmonar) r/c interrupción del flujo arterial.',
      intervencionesNIC: ['[4040] Cuidados cardíacos', '[3320] Oxigenoterapia', '[2300] Administración de medicación', '[6680] Monitorización de los signos vitales'],
      resultadosNOC: ['[0401] Estado circulatorio', '[0802] Signos vitales', '[1617] Autocontrol: cardiopatía'],
      planDeCuidados: 'Monitorización continua de ECG y signos vitales. Administración de oxígeno, antiagregantes, anticoagulantes, betabloqueantes y nitratos según pauta. Control del dolor con opiáceos si es preciso. Reposo absoluto y ambiente tranquilo. Preparación para posible angioplastia o fibrinolisis.',
      farmacosPrincipales: ['Ácido acetilsalicílico', 'Clopidogrel', 'Heparina', 'Morfina', 'Nitroglicerina', 'Atenolol'],
      clavesResumen: 'Causa: Oclusión coronaria. Diagnóstico clave: ECG (elevación ST) y troponinas. Tratamiento urgente: Reperfusión (ACTP o fibrinolisis). "Tiempo es músculo".'
    },
    {
      id: 'cardio-2',
      name: 'Insuficiencia Cardíaca Congestiva',
      sistema: System.CARDIOVASCULAR,
      etimologia: 'Incapacidad del corazón para bombear suficiente sangre para satisfacer las necesidades del cuerpo.',
      definicionClinica: 'Síndrome clínico complejo resultado de cualquier alteración, estructural o funcional, del llenado o de la eyección ventricular.',
      sintomatologia: ['Disnea de esfuerzo', 'Ortopnea', 'Edema en miembros inferiores', 'Fatiga', 'Taquicardia', 'Hepatomegalia'],
      diagnosticoNANDA: '[00029] Disminución del gasto cardíaco r/c alteración de la precarga, poscarga y/o contractilidad.',
      intervencionesNIC: ['[4040] Cuidados cardíacos', '[4120] Manejo de líquidos', '[0840] Cambio de posición', '[2314] Administración de medicación: IV'],
      resultadosNOC: ['[0400] Efectividad de la bomba cardíaca', '[0601] Equilibrio hídrico', '[0005] Tolerancia a la actividad'],
      planDeCuidados: 'Control estricto de diuresis y peso diario. Restricción de líquidos y sodio. Administración de diuréticos, IECAs, betabloqueantes. Oxigenoterapia según necesidad. Educación sobre signos de alarma.',
      farmacosPrincipales: ['Furosemida', 'Enalapril', 'Carvedilol', 'Espironolactona', 'Digoxina'],
      clavesResumen: 'Principal causa de hospitalización en >65 años. Clasificación NYHA funcional. Diagnóstico clave: péptidos natriuréticos (BNP) y ecocardiograma. Tratamiento se enfoca en reducir precarga y poscarga.'
    },
    {
      id: 'cardio-3',
      name: 'Hipertensión Arterial (HTA)',
      sistema: System.CARDIOVASCULAR,
      etimologia: 'Del griego "hiper-" (exceso) y latín "tensio" (presión). Presión arterial persistentemente elevada.',
      definicionClinica: 'Afección en la que la fuerza que ejerce la sangre contra las paredes de las arterias es lo suficientemente alta como para poder causar problemas de salud, como enfermedades cardíacas.',
      sintomatologia: ['Generalmente asintomática', 'Cefalea occipital', 'Mareos', 'Epistaxis', 'Visión borrosa'],
      diagnosticoNANDA: '[00204] Perfusión tisular periférica ineficaz r/c hipertensión.',
      intervencionesNIC: ['[4150] Regulación hemodinámica', '[5614] Enseñanza: dieta prescrita', '[5616] Enseñanza: medicamentos prescritos'],
      resultadosNOC: ['[0802] Signos vitales', '[1622] Conducta de cumplimiento: dieta prescrita', '[1837] Conocimiento: control de la enfermedad'],
      planDeCuidados: 'Monitorización de la PA. Educación sobre dieta hiposódica (dieta DASH), ejercicio regular, y abandono del tabaco. Administración de medicación antihipertensiva y enseñanza sobre sus efectos.',
      farmacosPrincipales: ['Hidroclorotiazida', 'Enalapril', 'Losartán', 'Amlodipino'],
      clavesResumen: 'El "asesino silencioso". Factor de riesgo principal para ACV, IAM, insuficiencia cardíaca y renal. El objetivo es <130/80 mmHg en la mayoría de pacientes.'
    },
    {
      id: 'cardio-4',
      name: 'Fibrilación Auricular (FA)',
      sistema: System.CARDIOVASCULAR,
      etimologia: 'Del latín "fibrillatio" (contracción rápida y desorganizada). Ritmo cardíaco irregular y a menudo muy rápido (arritmia) que puede provocar coágulos de sangre en el corazón.',
      definicionClinica: 'Taquiarritmia supraventricular caracterizada por una activación auricular descoordinada que produce un deterioro de la función mecánica auricular.',
      sintomatologia: ['Palpitaciones', 'Fatiga', 'Disnea', 'Mareo o síncope', 'Dolor torácico'],
      diagnosticoNANDA: '[00029] Disminución del gasto cardíaco r/c alteración del ritmo cardíaco.',
      intervencionesNIC: ['[4050] Manejo de la arritmia', '[4035] Administración de medicación: antiarrítmica', '[4110] Precauciones contra el embolismo'],
      resultadosNOC: ['[0400] Efectividad de la bomba cardíaca', '[0401] Estado circulatorio', '[0800] Termorregulación'],
      planDeCuidados: 'Monitorización ECG. Control de la frecuencia cardíaca (betabloqueantes, calcioantagonistas) o del ritmo (cardioversión). Anticoagulación para prevenir embolias (escala CHA2DS2-VASc).',
      farmacosPrincipales: ['Apixabán', 'Rivaroxabán', 'Bisoprolol', 'Diltiazem', 'Amiodarona'],
      clavesResumen: 'Arritmia sostenida más frecuente. Principal riesgo: ACV isquémico. ECG: ausencia de ondas P, ritmo RR irregular. El tratamiento se basa en control de frecuencia/ritmo y anticoagulación.'
    },
    {
      id: 'cardio-5',
      name: 'Angina de Pecho',
      sistema: System.CARDIOVASCULAR,
      etimologia: 'Del latín "angere" (estrechar) y "pectus" (pecho). Dolor torácico por isquemia miocárdica transitoria.',
      definicionClinica: 'Síndrome clínico caracterizado por dolor o malestar en el tórax, cuello, mandíbula, brazo u otras áreas, causado por isquemia miocárdica transitoria, sin llegar a producir necrosis.',
      sintomatologia: ['Dolor torácico opresivo que aparece con el esfuerzo', 'Se alivia con el reposo o nitroglicerina', 'Irradiación a brazo izquierdo, mandíbula o espalda', 'Duración de minutos (<20 min)', 'Puede acompañarse de disnea o diaforesis'],
      diagnosticoNANDA: '[00033] Riesgo de disminución de la perfusión tisular cardíaca r/c isquemia miocárdica.',
      intervencionesNIC: ['[4040] Cuidados cardíacos: agudos', '[2300] Administración de medicación', '[5616] Enseñanza: medicamentos prescritos', '[5510] Educación para la salud'],
      resultadosNOC: ['[0401] Estado circulatorio', '[1608] Control de síntomas', '[1837] Conocimiento: control de la enfermedad'],
      planDeCuidados: 'Durante el episodio agudo: reposo, monitorización, administración de nitroglicerina sublingual. Educación sobre factores de riesgo (dieta, ejercicio, tabaco), reconocimiento de síntomas y cuándo buscar ayuda médica urgente.',
      farmacosPrincipales: ['Nitroglicerina', 'Ácido acetilsalicílico', 'Bisoprolol', 'Atorvastatina'],
      clavesResumen: 'Dolor isquémico transitorio, no hay necrosis (troponinas negativas). Angina estable (predecible, con esfuerzo) vs. inestable (impredecible, en reposo, un SCA).'
    },
    {
      id: 'cardio-6',
      name: 'Endocarditis Infecciosa',
      sistema: System.CARDIOVASCULAR,
      etimologia: 'Del griego "endo-" (dentro), "kardia" (corazón) e "-itis" (inflamación). Infección del revestimiento interno del corazón.',
      definicionClinica: 'Infección microbiana del endocardio valvular o mural, que conduce a la formación de vegetaciones compuestas por plaquetas, fibrina, microorganismos y células inflamatorias.',
      sintomatologia: ['Fiebre prolongada', 'Soplos cardíacos nuevos o cambiantes', 'Fenómenos embólicos (ACV, isquemia en extremidades)', 'Hemorragias en astilla (uñas)', 'Lesiones de Janeway (palmas/plantas)', 'Nódulos de Osler (dedos)'],
      diagnosticoNANDA: '[00004] Riesgo de infección r/c procedimiento invasivo o puerta de entrada de microorganismos.',
      intervencionesNIC: ['[6540] Control de infecciones', '[4030] Administración de productos sanguíneos', '[2314] Administración de medicación: IV', '[6680] Monitorización de los signos vitales'],
      resultadosNOC: ['[0703] Severidad de la infección', '[0401] Estado circulatorio', '[1902] Control del riesgo'],
      planDeCuidados: 'Antibioticoterapia IV prolongada (4-6 semanas) según hemocultivos. Monitorización de signos de insuficiencia cardíaca y embolismos. Higiene bucal estricta. Posible necesidad de cirugía de reemplazo valvular.',
      farmacosPrincipales: ['Penicilina', 'Vancomicina', 'Ceftriaxona', 'Gentamicina'],
      clavesResumen: 'Urgencia médica. Criterios de Duke para el diagnóstico (hemocultivos + ecocardiograma). Principal riesgo en usuarios de drogas IV y portadores de prótesis valvulares.'
    },
    // Respiratorio
    {
      id: 'resp-1',
      name: 'Enfermedad Pulmonar Obstructiva Crónica (EPOC)',
      sistema: System.RESPIRATORIO,
      etimologia: 'Del latín "obstructio" (obstrucción). Enfermedad crónica y progresiva que dificulta la respiración.',
      definicionClinica: 'Enfermedad pulmonar caracterizada por una limitación del flujo aéreo persistente, generalmente progresiva y asociada a una respuesta inflamatoria crónica aumentada en las vías aéreas y el pulmón a partículas o gases nocivos.',
      sintomatologia: ['Disnea progresiva', 'Tos crónica', 'Producción de esputo', 'Sibilancias', 'Opresión torácica'],
      diagnosticoNANDA: '[00032] Patrón respiratorio ineficaz r/c fatiga de los músculos respiratorios y obstrucción bronquial.',
      intervencionesNIC: ['[3140] Manejo de las vías aéreas', '[3350] Monitorización respiratoria', '[3230] Fisioterapia respiratoria', '[3320] Oxigenoterapia'],
      resultadosNOC: ['[0415] Estado respiratorio', '[0403] Ventilación', '[0410] Estado respiratorio: permeabilidad de las vías respiratorias'],
      planDeCuidados: 'Administración de broncodilatadores y corticoides inhalados. Oxigenoterapia a largo plazo si hay hipoxemia. Fisioterapia respiratoria para drenaje de secreciones. Educación para el autocuidado: dejar de fumar, vacunación, reconocer exacerbaciones.',
      farmacosPrincipales: ['Salbutamol', 'Budesonida/Formoterol', 'Tiotropio', 'Prednisona (en exacerbaciones)'],
      clavesResumen: 'Principal factor de riesgo: tabaquismo. Diagnóstico: espirometría (VEF1/CVF < 0.7 post-broncodilatador). Dos fenotipos principales: bronquitis crónica ("blue bloater") y enfisema ("pink puffer").'
    },
    {
      id: 'resp-2',
      name: 'Asma',
      sistema: System.RESPIRATORIO,
      etimologia: 'Del griego "asthma" (respiración difícil, jadeo).',
      definicionClinica: 'Enfermedad inflamatoria crónica de las vías respiratorias, en la que participan diversas células y mediadores. Se asocia con hiperreactividad bronquial y una obstrucción reversible del flujo aéreo.',
      sintomatologia: ['Sibilancias', 'Disnea', 'Opresión torácica', 'Tos (especialmente nocturna o al despertar)'],
      diagnosticoNANDA: '[00030] Deterioro del intercambio de gases r/c obstrucción de las vías aéreas por broncoespasmo y edema.',
      intervencionesNIC: ['[3140] Manejo de las vías aéreas', '[3250] Manejo del asma', '[6480] Manejo del ambiente', '[2300] Administración de medicación'],
      resultadosNOC: ['[0410] Estado respiratorio: permeabilidad de las vías respiratorias', '[1609] Autocontrol: asma', '[0415] Estado respiratorio'],
      planDeCuidados: 'Educación al paciente sobre el uso de inhaladores y el plan de acción para crisis. Administración de broncodilatadores de acción corta para rescate y corticoides inhalados como tratamiento de mantenimiento. Evitar desencadenantes.',
      farmacosPrincipales: ['Salbutamol', 'Budesonida', 'Fluticasona/Salmeterol', 'Montelukast', 'Prednisona (en crisis)'],
      clavesResumen: 'Enfermedad crónica más común en niños. Obstrucción reversible al flujo aéreo. Tratamiento escalonado según el control de los síntomas. Clave: educación para el autocontrol.'
    },
    {
      id: 'resp-3',
      name: 'Neumonía Adquirida en la Comunidad (NAC)',
      sistema: System.RESPIRATORIO,
      etimologia: 'Del griego "pneumon" (pulmón). Infección que inflama los sacos aéreos de uno o ambos pulmones.',
      definicionClinica: 'Infección aguda del parénquima pulmonar en un paciente que no ha sido hospitalizado recientemente.',
      sintomatologia: ['Fiebre', 'Tos productiva (esputo purulento)', 'Dolor torácico pleurítico', 'Disnea', 'Crepitantes en la auscultación'],
      diagnosticoNANDA: '[00031] Limpieza ineficaz de las vías aéreas r/c proceso infeccioso y aumento de secreciones.',
      intervencionesNIC: ['[3160] Aspiración de las vías aéreas', '[3230] Fisioterapia respiratoria', '[6540] Control de infecciones', '[3900] Regulación de la temperatura'],
      resultadosNOC: ['[0410] Estado respiratorio: permeabilidad de las vías respiratorias', '[0703] Severidad de la infección', '[0800] Termorregulación'],
      planDeCuidados: 'Antibioticoterapia empírica según guías locales. Hidratación adecuada. Oxigenoterapia si hay hipoxemia. Fisioterapia respiratoria para movilizar secreciones. Control de la fiebre.',
      farmacosPrincipales: ['Amoxicilina', 'Azitromicina', 'Levofloxacino', 'Ceftriaxona'],
      clavesResumen: 'Diagnóstico por clínica y radiografía de tórax (infiltrado). Escala CURB-65 para decidir ingreso hospitalario. Agente causal más común: Streptococcus pneumoniae.'
    },
    {
      id: 'resp-4',
      name: 'Tuberculosis Pulmonar (TBC)',
      sistema: System.RESPIRATORIO,
      etimologia: 'Del latín "tuberculum" (pequeño nódulo). Enfermedad infecciosa bacteriana que afecta principalmente a los pulmones.',
      definicionClinica: 'Enfermedad infecciosa crónica causada por Mycobacterium tuberculosis, que se transmite por vía aérea y se caracteriza por la formación de granulomas en los tejidos, principalmente en los pulmones.',
      sintomatologia: ['Tos persistente (>2 semanas)', 'Hemoptisis', 'Fiebre y sudoración nocturna', 'Pérdida de peso', 'Astenia', 'Dolor torácico'],
      diagnosticoNANDA: '[00031] Limpieza ineficaz de las vías aéreas r/c aumento de secreciones y tos ineficaz.',
      intervencionesNIC: ['[6550] Protección contra las infecciones (aislamiento aéreo)', '[5602] Enseñanza: proceso de la enfermedad', '[2300] Administración de medicación', '[5210] Guía de anticipación'],
      resultadosNOC: ['[0703] Severidad de la infección', '[1623] Conducta de cumplimiento: medicación', '[1842] Conocimiento: control de la infección'],
      planDeCuidados: 'Aislamiento respiratorio en habitación con presión negativa hasta que el tratamiento sea efectivo. Administración de tratamiento antibiótico combinado y prolongado (Rifampicina, Isoniazida, Pirazinamida, Etambutol). Educación sobre la importancia de la adherencia para evitar resistencias. Soporte nutricional.',
      farmacosPrincipales: ['Isoniazida', 'Rifampicina', 'Pirazinamida', 'Etambutol'],
      clavesResumen: 'Enfermedad de declaración obligatoria. Diagnóstico: baciloscopia de esputo, cultivo, prueba de Mantoux/IGRA, Rx tórax (cavernas en lóbulos superiores). Tratamiento directamente observado (TDO) para asegurar cumplimiento.'
    },
    {
      id: 'resp-5',
      name: 'Derrame Pleural',
      sistema: System.RESPIRATORIO,
      etimologia: 'Acumulación anormal de líquido en el espacio pleural, entre el pulmón y la pared torácica.',
      definicionClinica: 'Acumulación patológica de líquido en el espacio pleural que excede la capacidad de reabsorción. Puede ser un trasudado (causas sistémicas) o un exudado (causas locales).',
      sintomatologia: ['Disnea', 'Dolor torácico pleurítico', 'Tos seca', 'Disminución del murmullo vesicular y matidez a la percusión en la zona afectada'],
      diagnosticoNANDA: '[00032] Patrón respiratorio ineficaz r/c compresión pulmonar por acumulación de líquido.',
      intervencionesNIC: ['[3350] Monitorización respiratoria', '[1874] Cuidados del drenaje torácico', '[3140] Manejo de las vías aéreas', '[1400] Manejo del dolor'],
      resultadosNOC: ['[0415] Estado respiratorio', '[0403] Ventilación', '[2102] Nivel de dolor'],
      planDeCuidados: 'Vigilar la función respiratoria. Preparación y asistencia en la toracocentesis diagnóstica/terapéutica. Cuidados del drenaje torácico si se coloca. Manejo del dolor. Tratamiento de la causa subyacente.',
      farmacosPrincipales: ['Diuréticos (si es por ICC)', 'Antibióticos (si es paraneumónico)', 'Analgésicos'],
      clavesResumen: 'Signo de una enfermedad subyacente, no un diagnóstico final. Criterios de Light para diferenciar trasudado de exudado en el líquido pleural. Causas comunes: ICC (trasudado), neumonía, cáncer (exudado).'
    },
    // Digestivo
    {
      id: 'digestivo-1',
      name: 'Enfermedad de Crohn',
      sistema: System.DIGESTIVO,
      etimologia: 'Nombrada por Burrill Crohn. Enfermedad inflamatoria intestinal crónica.',
      definicionClinica: 'Enfermedad inflamatoria intestinal de causa desconocida que puede afectar cualquier parte del tracto gastrointestinal, desde la boca hasta el ano. Se caracteriza por una inflamación transmural (afecta a todo el espesor de la pared intestinal) y segmentaria (áreas afectadas alternan con áreas sanas).',
      sintomatologia: ['Dolor abdominal (típicamente en fosa ilíaca derecha)', 'Diarrea crónica (no siempre sanguinolenta)', 'Pérdida de peso', 'Fiebre', 'Fístulas y abscesos perianales'],
      diagnosticoNANDA: '[00013] Diarrea r/c proceso inflamatorio intestinal.',
      intervencionesNIC: ['[0460] Manejo de la diarrea', '[1100] Manejo de la nutrición', '[1400] Manejo del dolor', '[5230] Mejorar el afrontamiento'],
      resultadosNOC: ['[0501] Eliminación intestinal', '[1004] Estado nutricional', '[1302] Afrontamiento de problemas'],
      planDeCuidados: 'Manejo nutricional para evitar déficits. Administración de antiinflamatorios (aminosalicilatos, corticoides) e inmunosupresores/biológicos. Cuidado de la piel perianal. Apoyo emocional para enfermedad crónica.',
      farmacosPrincipales: ['Mesalazina', 'Prednisona', 'Azatioprina', 'Infliximab', 'Adalimumab'],
      clavesResumen: 'Enfermedad crónica que cursa en brotes. Afectación "en empedrado" y granulomas no caseificantes en biopsia. Aumenta el riesgo de cáncer colorrectal. El tabaco empeora la enfermedad.'
    },
    {
      id: 'digestivo-2',
      name: 'Pancreatitis Aguda',
      sistema: System.DIGESTIVO,
      etimologia: 'Del griego "pan-" (todo), "kreas" (carne) e "-itis" (inflamación). Inflamación aguda del páncreas.',
      definicionClinica: 'Proceso inflamatorio agudo del páncreas, con afectación variable de otros tejidos y órganos regionales o a distancia, desencadenado por la activación intrapancreática de las enzimas digestivas.',
      sintomatologia: ['Dolor epigástrico intenso, súbito, irradiado "en cinturón" a la espalda', 'Náuseas y vómitos', 'Fiebre', 'Taquicardia', 'Signo de Cullen (equimosis periumbilical)', 'Signo de Grey-Turner (equimosis en flancos)'],
      diagnosticoNANDA: '[00132] Dolor agudo r/c inflamación y autodigestión del páncreas.',
      intervencionesNIC: ['[1400] Manejo del dolor', '[4120] Manejo de líquidos', '[1100] Manejo de la nutrición (dieta absoluta)', '[2314] Administración de medicación: IV'],
      resultadosNOC: ['[1605] Control del dolor', '[2102] Nivel de dolor', '[0601] Equilibrio hídrico'],
      planDeCuidados: 'Dieta absoluta para reposo pancreático. Fluidoterapia intravenosa agresiva. Analgesia potente (opiáceos). Monitorización de signos vitales y diuresis. Vigilancia de complicaciones (pseudoquiste, necrosis, fallo multiorgánico).',
      farmacosPrincipales: ['Suero Ringer Lactato', 'Morfina', 'Metamizol', 'Omeprazol'],
      clavesResumen: 'Urgencia abdominal. Causas principales: litiasis biliar y alcohol. Diagnóstico: clínica + elevación de amilasa/lipasa (>3 veces lo normal). Criterios de Ranson/BISAP para evaluar la gravedad.'
    },
    {
      id: 'digestivo-3',
      name: 'Cirrosis Hepática',
      sistema: System.DIGESTIVO,
      etimologia: 'Del griego "kirrhos" (amarillo anaranjado), por el color del hígado. Fase tardía de la cicatrización (fibrosis) del hígado.',
      definicionClinica: 'Estadio final de múltiples enfermedades hepáticas crónicas, caracterizado por la sustitución de la arquitectura normal del hígado por nódulos de regeneración anormales rodeados de tejido fibroso, lo que conduce a la insuficiencia hepatocelular e hipertensión portal.',
      sintomatologia: ['Ictericia', 'Ascitis', 'Edemas', 'Ginecomastia, arañas vasculares', 'Hemorragia por varices esofágicas', 'Encefalopatía hepática'],
      diagnosticoNANDA: '[00025] Riesgo de desequilibrio del volumen de líquidos r/c compromiso de los mecanismos reguladores (hipertensión portal, hipoalbuminemia).',
      intervencionesNIC: ['[4120] Manejo de líquidos', '[1100] Manejo de la nutrición', '[4010] Precauciones contra la hemorragia', '[2590] Vigilancia neurológica'],
      resultadosNOC: ['[0601] Equilibrio hídrico', '[1004] Estado nutricional', '[0913] Estado neurológico: conciencia'],
      planDeCuidados: 'Restricción de sodio y manejo de diuréticos para la ascitis. Profilaxis de hemorragia por varices con betabloqueantes. Dieta hipoproteica si hay encefalopatía. Vigilancia de signos de sangrado y estado neurológico. Educación sobre abstinencia alcohólica.',
      farmacosPrincipales: ['Espironolactona', 'Furosemida', 'Propranolol', 'Lactulosa', 'Rifaximina'],
      clavesResumen: 'Proceso irreversible. Causas principales: alcohol, hepatitis virales (B, C), hígado graso no alcohólico. La escala de Child-Pugh clasifica la gravedad. Complicaciones mortales: hemorragia digestiva, peritonitis bacteriana espontánea.'
    },
    // Neurologia
    {
      id: 'neuro-1',
      name: 'Accidente Cerebrovascular (ACV) Isquémico',
      sistema: System.NEUROLOGIA_SENTIDOS,
      etimologia: 'Déficit neurológico súbito atribuido a una lesión focal del sistema nervioso central por una causa vascular.',
      definicionClinica: 'Episodio de disfunción neurológica aguda causado por infarto cerebral, de la médula espinal o de la retina, debido a la oclusión de un vaso sanguíneo.',
      sintomatologia: ['Hemiparesia o hemiplejía súbita', 'Disartria o afasia', 'Alteración visual (hemianopsia)', 'Confusión', 'Cefalea intensa'],
      diagnosticoNANDA: '[00047] Riesgo de deterioro de la integridad cutánea r/c inmovilidad física.',
      intervencionesNIC: ['[2620] Monitorización neurológica', '[0740] Cuidados del paciente encamado', '[1804] Ayuda con el autocuidado: deglución', '[6490] Prevención de caídas'],
      resultadosNOC: ['[0909] Estado neurológico', '[1913] Estado neurológico: control motor central', '[1101] Integridad tisular: piel y membranas mucosas'],
      planDeCuidados: 'Monitorización neurológica (escala de Glasgow, NIHSS). Mantener vía aérea permeable. Control de TA, glucemia y temperatura. Terapia trombolítica si es candidato ("ventana terapéutica"). Cuidados posturales y prevención de UPP. Rehabilitación precoz.',
      farmacosPrincipales: ['Alteplasa (rt-PA)', 'Ácido acetilsalicílico', 'Atorvastatina', 'Heparina de bajo peso molecular (profilaxis TEV)'],
      clavesResumen: 'Actuación rápida es crucial. "Tiempo es cerebro". Escala FAST (Face, Arms, Speech, Time) para reconocimiento. Diagnóstico diferencial con ACV hemorrágico mediante TAC craneal urgente.'
    },
    {
      id: 'neuro-2',
      name: 'Meningitis Bacteriana',
      sistema: System.NEUROLOGIA_SENTIDOS,
      etimologia: 'Del griego "meninx" (membrana) y el sufijo "-itis" (inflamación).',
      definicionClinica: 'Inflamación de las meninges causada por una infección bacteriana, que puede provocar secuelas neurológicas graves o la muerte.',
      sintomatologia: ['Fiebre alta', 'Cefalea intensa', 'Rigidez de nuca (signo de Kernig/Brudzinski +)', 'Alteración del estado mental', 'Fotofobia', 'Rash petequial (meningococo)'],
      diagnosticoNANDA: '[00049] Disminución de la capacidad adaptativa intracraneal r/c inflamación cerebral.',
      intervencionesNIC: ['[2590] Monitorización de la presión intracraneal (PIC)', '[2620] Monitorización neurológica', '[6550] Protección contra las infecciones (aislamiento)'],
      resultadosNOC: ['[0909] Estado neurológico', '[0703] Severidad de la infección', '[2102] Nivel de dolor'],
      planDeCuidados: 'Inicio inmediato de antibioticoterapia empírica IV tras la toma de hemocultivos. Punción lumbar para diagnóstico (si no hay contraindicación). Aislamiento respiratorio (gotas) durante las primeras 24h de tratamiento. Control de la fiebre y manejo de la PIC.',
      farmacosPrincipales: ['Ceftriaxona', 'Vancomicina', 'Dexametasona (para reducir inflamación y secuelas)'],
      clavesResumen: 'Emergencia neurológica. "Tiempo es neurona". La punción lumbar es diagnóstica (análisis de LCR). Agentes comunes: Neisseria meningitidis, Streptococcus pneumoniae.'
    },
    {
      id: 'neuro-3',
      name: 'Epilepsia',
      sistema: System.NEUROLOGIA_SENTIDOS,
      etimologia: 'Del griego "epilambanein" (agarrar, atacar). Trastorno neurológico con convulsiones recurrentes.',
      definicionClinica: 'Enfermedad cerebral crónica caracterizada por una predisposición duradera a generar crisis epilépticas y por las consecuencias neurobiológicas, cognitivas, psicológicas y sociales de esta condición.',
      sintomatologia: ['Crisis convulsivas (tónico-clónicas)', 'Ausencias', 'Movimientos automáticos', 'Aura (sensación pre-crisis)', 'Confusión post-crisis (periodo postictal)'],
      diagnosticoNANDA: '[00052] Riesgo de traumatismo r/c pérdida de la coordinación muscular durante la convulsión.',
      intervencionesNIC: ['[6490] Prevención de caídas', '[2680] Manejo de las convulsiones', '[5616] Enseñanza: medicamentos prescritos', '[5510] Educación para la salud'],
      resultadosNOC: ['[1909] Conducta de prevención de caídas', '[1914] Autocontrol: epilepsia', '[2808] Seguridad en el hogar'],
      planDeCuidados: 'Durante la crisis: proteger al paciente de lesiones, no introducir objetos en la boca, colocar de lado. Post-crisis: vigilar estado de conciencia y vía aérea. Educación sobre la importancia de la adherencia al tratamiento farmacológico y evitar desencadenantes (falta de sueño, alcohol).',
      farmacosPrincipales: ['Ácido valproico', 'Levetiracetam', 'Lamotrigina', 'Diazepam (en crisis)'],
      clavesResumen: 'No todas las convulsiones son epilepsia. Diagnóstico se basa en la historia clínica y EEG. Tratamiento busca el control de las crisis con mínimos efectos secundarios. La seguridad del paciente durante las crisis es prioritaria.'
    },
    {
        id: 'neuro-4',
        name: 'Enfermedad de Parkinson',
        sistema: System.NEUROLOGIA_SENTIDOS,
        etimologia: 'Nombrada por James Parkinson, quien la describió en 1817. Trastorno neurodegenerativo del movimiento.',
        definicionClinica: 'Enfermedad neurodegenerativa crónica y progresiva del sistema nervioso central que afecta principalmente a las neuronas dopaminérgicas en la sustancia negra, provocando un trastorno del movimiento.',
        sintomatologia: ['Tétrada clásica: Temblor en reposo ("pill-rolling")', 'Bradicinesia (lentitud de movimiento)', 'Rigidez muscular (en "rueda dentada")', 'Inestabilidad postural', 'Marcha festinante', 'Cara de máscara (hipomimia)'],
        diagnosticoNANDA: '[00109] Déficit de autocuidado: vestido r/c deterioro neuromuscular.',
        intervencionesNIC: ['[6490] Prevención de caídas', '[1800] Ayuda con el autocuidado', '[0224] Terapia de ejercicios: movilidad articular', '[5616] Enseñanza: medicamentos prescritos'],
        resultadosNOC: ['[0300] Autocuidados: actividades de la vida diaria (AVD)', '[1909] Conducta de prevención de caídas', '[0208] Movilidad'],
        planDeCuidados: 'Maximizar la seguridad del paciente para prevenir caídas. Administrar la medicación en horarios estrictos para evitar fluctuaciones motoras. Fomentar la independencia en las AVD. Terapia física y ocupacional. Adaptaciones en el hogar. Educación al paciente y familia sobre la progresión de la enfermedad.',
        farmacosPrincipales: ['Levodopa/Carbidopa', 'Pramipexol', 'Rasagilina', 'Amantadina'],
        clavesResumen: 'Causa: pérdida de neuronas productoras de dopamina. El diagnóstico es clínico. El tratamiento es sintomático y busca reponer la dopamina. No tiene cura, pero el tratamiento mejora significativamente la calidad de vida.'
    },
     {
      id: 'neuro-5',
      name: 'Esclerosis Múltiple',
      sistema: System.NEUROLOGIA_SENTIDOS,
      etimologia: 'Del griego "skleros" (duro), refiriéndose a las placas de tejido cicatricial en el SNC.',
      definicionClinica: 'Enfermedad autoinmune, inflamatoria y desmielinizante del sistema nervioso central que afecta al cerebro y la médula espinal, causando una amplia gama de síntomas neurológicos que aparecen en brotes o de forma progresiva.',
      sintomatologia: ['Fatiga', 'Alteraciones sensitivas (parestesias)', 'Debilidad muscular', 'Alteraciones visuales (neuritis óptica)', 'Espasticidad', 'Problemas de equilibrio y coordinación (ataxia)'],
      diagnosticoNANDA: '[00085] Deterioro de la movilidad física r/c debilidad muscular, espasticidad y/o pérdida del equilibrio.',
      intervencionesNIC: ['[0226] Terapia de ejercicios: control muscular', '[0180] Manejo de la energía', '[6490] Prevención de caídas', '[5400] Potenciación de la autoestima'],
      resultadosNOC: ['[0208] Movilidad', '[0001] Resistencia', '[1305] Adaptación psicosocial: cambio de vida'],
      planDeCuidados: 'Manejo de la fatiga con planificación de actividades. Prevención de caídas. Administración de tratamientos modificadores de la enfermedad. Manejo de síntomas como la espasticidad y el dolor. Apoyo emocional y educación para el autocontrol de la enfermedad crónica.',
      farmacosPrincipales: ['Interferón beta', 'Glatiramero', 'Fingolimod', 'Natalizumab', 'Metilprednisolona (en brotes)'],
      clavesResumen: 'Enfermedad crónica más común en adultos jóvenes. El diagnóstico se basa en la clínica y RMN (lesiones desmielinizantes diseminadas en tiempo y espacio). El tratamiento busca reducir la frecuencia y severidad de los brotes.'
    },
    {
      id: 'neuro-6',
      name: 'Enfermedad de Alzheimer',
      sistema: System.NEUROLOGIA_SENTIDOS,
      etimologia: 'Nombrada por Alois Alzheimer. Enfermedad neurodegenerativa que causa demencia.',
      definicionClinica: 'Trastorno neurodegenerativo progresivo que se caracteriza por el deterioro de la memoria, el pensamiento y la conducta. Es la causa más común de demencia y se asocia con la presencia de placas de beta-amiloide y ovillos neurofibrilares en el cerebro.',
      sintomatologia: ['Pérdida de memoria reciente', 'Dificultad para planificar o resolver problemas', 'Desorientación en tiempo y lugar', 'Cambios en el humor o la personalidad', 'Afasia (dificultad con el lenguaje)', 'Apraxia (incapacidad para realizar tareas motoras)'],
      diagnosticoNANDA: '[00131] Deterioro de la memoria r/c alteración neurológica.',
      intervencionesNIC: ['[4720] Estimulación cognitiva', '[6486] Manejo ambiental: seguridad', '[5330] Control del humor', '[5270] Apoyo emocional'],
      resultadosNOC: ['[0900] Cognición', '[1301] Adaptación del cuidador principal', '[2604] Normalización familiar'],
      planDeCuidados: 'Proporcionar un entorno seguro, estructurado y tranquilo. Utilizar estrategias de comunicación sencillas y claras. Estimulación cognitiva y orientación a la realidad. Fomentar la independencia en AVD tanto como sea posible. Apoyo y educación a la familia/cuidadores.',
      farmacosPrincipales: ['Donepezilo', 'Rivastigmina', 'Galantamina', 'Memantina'],
      clavesResumen: 'Causa más frecuente de demencia. El diagnóstico es de exclusión. El tratamiento farmacológico es sintomático y busca ralentizar la progresión. El cuidado se centra en la seguridad del paciente y el apoyo al cuidador.'
    },
    {
      id: 'neuro-7',
      name: 'Glaucoma',
      sistema: System.NEUROLOGIA_SENTIDOS,
      etimologia: 'Del griego "glaukos" (verde azulado), por el color que podía tomar la pupila.',
      definicionClinica: 'Grupo de enfermedades oculares que provocan un daño progresivo e irreversible en el nervio óptico, generalmente asociado a un aumento de la presión intraocular (PIO), lo que conduce a una pérdida característica del campo visual.',
      sintomatologia: ['Generalmente asintomático en fases iniciales (glaucoma de ángulo abierto)', 'Pérdida de visión periférica (visión en túnel)', 'Dolor ocular intenso, náuseas, visión de halos (en glaucoma agudo de ángulo cerrado)'],
      diagnosticoNANDA: '[00155] Riesgo de caídas r/c deterioro de la visión.',
      intervencionesNIC: ['[6490] Prevención de caídas', '[2310] Administración de medicación: oftálmica', '[5602] Enseñanza: proceso de la enfermedad', '[5510] Educación para la salud'],
      resultadosNOC: ['[1909] Conducta de prevención de caídas', '[1623] Conducta de cumplimiento: medicación', '[1806] Conocimiento: recursos sanitarios'],
      planDeCuidados: 'Educación sobre la importancia de la adherencia al tratamiento con colirios para controlar la PIO. Enseñanza de la técnica correcta de instilación de gotas. Adaptaciones en el hogar para prevenir caídas. Apoyo para afrontar la pérdida de visión progresiva.',
      farmacosPrincipales: ['Latanoprost', 'Timolol', 'Dorzolamida', 'Pilocarpina'],
      clavesResumen: 'Causa principal de ceguera irreversible en el mundo. El daño es irreversible, por lo que la detección precoz es clave. El tratamiento se centra en disminuir la PIO para frenar la progresión.'
    },
    // Endocrino
    {
      id: 'endocrino-1',
      name: 'Diabetes Mellitus Tipo 2',
      sistema: System.ENDOCRINO_METABOLICO,
      etimologia: 'Del griego "diabetes" (pasar a través) y latín "mellitus" (miel). Enfermedad metabólica con hiperglucemia.',
      definicionClinica: 'Trastorno metabólico caracterizado por hiperglucemia crónica debido a una combinación de resistencia a la insulina y una secreción de insulina relativamente deficiente.',
      sintomatologia: ['Poliuria', 'Polidipsia', 'Polifagia', 'Pérdida de peso inexplicada', 'Fatiga', 'Visión borrosa'],
      diagnosticoNANDA: '[00179] Riesgo de nivel de glucemia inestable.',
      intervencionesNIC: ['[2120] Manejo de la hiperglucemia', '[2130] Manejo de la hipoglucemia', '[5602] Enseñanza: proceso de la enfermedad', '[5614] Enseñanza: dieta prescrita'],
      resultadosNOC: ['[2300] Nivel de glucemia', '[1820] Conocimiento: control de la diabetes', '[1619] Autocontrol: diabetes'],
      planDeCuidados: 'Educación diabetológica (autocontrol de glucemia, dieta, ejercicio). Administración de antidiabéticos orales o insulina. Cuidado de los pies. Detección de complicaciones (retinopatía, nefropatía, neuropatía).',
      farmacosPrincipales: ['Metformina', 'Gliclazida', 'Sitagliptina', 'Empagliflozina', 'Insulina glargina'],
      clavesResumen: 'Factor de riesgo principal: obesidad y sedentarismo. Diagnóstico: HbA1c, glucemia basal, test de sobrecarga oral. El manejo se basa en los 3 pilares: dieta, ejercicio y medicación.'
    },
    {
      id: 'endocrino-2',
      name: 'Cetoacidosis Diabética (CAD)',
      sistema: System.ENDOCRINO_METABOLICO,
      etimologia: 'Del griego "ketos" (cuerpo cetónico) y "acidus" (ácido). Complicación aguda de la diabetes por déficit de insulina.',
      definicionClinica: 'Complicación metabólica aguda de la diabetes caracterizada por hiperglucemia, hipercetonemia y acidosis metabólica.',
      sintomatologia: ['Poliuria, polidipsia', 'Dolor abdominal, náuseas, vómitos', 'Aliento afrutado (cetónico)', 'Respiración de Kussmaul (rápida y profunda)', 'Deshidratación severa', 'Alteración del nivel de conciencia'],
      diagnosticoNANDA: '[00027] Déficit de volumen de líquidos r/c diuresis osmótica.',
      intervencionesNIC: ['[2080] Manejo de líquidos y electrólitos', '[2120] Manejo de la hiperglucemia', '[4238] Flebotomía: muestra de sangre venosa'],
      resultadosNOC: ['[0601] Equilibrio hídrico', '[0600] Equilibrio electrolítico y ácido-base', '[2300] Nivel de glucemia'],
      planDeCuidados: 'Tratamiento basado en 3 pilares: fluidoterapia intensiva (suero salino), insulinoterapia IV en perfusión continua y reposición de potasio. Monitorización horaria de glucemia, electrolitos y estado ácido-base.',
      farmacosPrincipales: ['Insulina rápida IV', 'Suero salino fisiológico 0.9%', 'Cloruro potásico'],
      clavesResumen: 'Urgencia médica. Más común en DM tipo 1. Desencadenantes: infección, debut diabético, abandono de insulina. La corrección debe ser gradual para evitar edema cerebral.'
    },
    {
      id: 'endocrino-3',
      name: 'Hipotiroidismo',
      sistema: System.ENDOCRINO_METABOLICO,
      etimologia: 'Del griego "hipo-" (debajo), "thyreos" (escudo) y "eidos" (forma). Déficit de hormonas tiroideas.',
      definicionClinica: 'Síndrome clínico resultante de una producción deficiente de hormonas tiroideas por la glándula tiroides, lo que provoca una ralentización general del metabolismo.',
      sintomatologia: ['Fatiga, letargia', 'Aumento de peso', 'Intolerancia al frío', 'Piel seca, cabello quebradizo', 'Bradicardia', 'Estreñimiento'],
      diagnosticoNANDA: '[00092] Intolerancia a la actividad r/c metabolismo basal disminuido.',
      intervencionesNIC: ['[1850] Fomentar el sueño', '[0480] Cuidados del cabello', '[3540] Prevención de úlceras por presión', '[2380] Manejo de la medicación'],
      resultadosNOC: ['[0005] Tolerancia a la actividad', '[2008] Estado de comodidad', '[3015] Autocontrol: hipotiroidismo'],
      planDeCuidados: 'Administración de levotiroxina en ayunas. Educación sobre la cronicidad del tratamiento y la necesidad de controles analíticos periódicos. Vigilar signos de sobredosificación (tirotoxicosis).',
      farmacosPrincipales: ['Levotiroxina sódica'],
      clavesResumen: 'Causa más común en zonas con suficiente yodo: tiroiditis de Hashimoto (autoinmune). Diagnóstico: TSH elevada, T4 libre baja. Tratamiento es de reemplazo hormonal de por vida.'
    },
    {
      id: 'endocrino-4',
      name: 'Hipertiroidismo',
      sistema: System.ENDOCRINO_METABOLICO,
      etimologia: 'Del griego "hiper-" (exceso). Producción excesiva de hormonas tiroideas.',
      definicionClinica: 'Síndrome clínico resultante de la exposición de los tejidos a concentraciones excesivas de hormonas tiroideas circulantes.',
      sintomatologia: ['Pérdida de peso con aumento de apetito', 'Nerviosismo, ansiedad', 'Intolerancia al calor, sudoración', 'Taquicardia, palpitaciones', 'Temblor fino', 'Exoftalmos (en Enfermedad de Graves)'],
      diagnosticoNANDA: '[00146] Ansiedad r/c estimulación del sistema nervioso central por exceso de hormonas tiroideas.',
      intervencionesNIC: ['[4040] Cuidados cardíacos', '[0500] Fomento de la nutrición', '[5820] Disminución de la ansiedad', '[2380] Manejo de la medicación'],
      resultadosNOC: ['[1211] Nivel de ansiedad', '[0802] Signos vitales', '[1004] Estado nutricional'],
      planDeCuidados: 'Monitorización de signos vitales. Administración de fármacos antitiroideos y betabloqueantes. Proporcionar un ambiente tranquilo. Dieta hipercalórica. Cuidados oculares si hay exoftalmos. Preparación para tratamiento con yodo radioactivo o tiroidectomía.',
      farmacosPrincipales: ['Metimazol', 'Carbimazol', 'Propiltiouracilo', 'Propranolol'],
      clavesResumen: 'Causa más común: Enfermedad de Graves (autoinmune). Diagnóstico: TSH suprimida, T4 libre elevada. Riesgo de "tormenta tiroidea", una emergencia médica.'
    },
    {
      id: 'endocrino-5',
      name: 'Síndrome de Cushing',
      sistema: System.ENDOCRINO_METABOLICO,
      etimologia: 'Nombrado por Harvey Cushing. Conjunto de signos y síntomas resultantes de la exposición prolongada a un exceso de cortisol.',
      definicionClinica: 'Trastorno hormonal causado por la exposición prolongada de los tejidos del cuerpo a niveles altos de la hormona cortisol. Puede ser iatrogénico (por corticoides) o endógeno (por tumores).',
      sintomatologia: ['Obesidad central (troncular)', 'Cara de luna llena (facies pletórica)', 'Giba de búfalo (acúmulo de grasa dorsocervical)', 'Estrías rojo-vinosas', 'Hipertensión, hiperglucemia', 'Debilidad muscular, osteoporosis'],
      diagnosticoNANDA: '[00125] Impotencia r/c efectos de la enfermedad sobre la imagen corporal y el funcionamiento.',
      intervencionesNIC: ['[5220] Potenciación de la imagen corporal', '[6610] Identificación de riesgos (fracturas, infecciones)', '[2120] Manejo de la hiperglucemia', '[4150] Regulación hemodinámica'],
      resultadosNOC: ['[1200] Imagen corporal', '[1908] Detección del riesgo', '[1300] Aceptación: estado de salud'],
      planDeCuidados: 'Monitorización de glucemia, TA y peso. Prevención de infecciones y fracturas. Dieta baja en sodio y carbohidratos, rica en potasio y proteínas. Apoyo emocional por los cambios en la imagen corporal. Cuidados pre y postoperatorios si la causa es un tumor.',
      farmacosPrincipales: ['Ketoconazol', 'Metopirona', 'Pasireotida'],
      clavesResumen: 'La causa más frecuente es el uso de corticoides exógenos. Si es endógeno, hay que localizar el tumor (hipofisario, suprarrenal, ectópico). La retirada de corticoides debe ser muy gradual para evitar insuficiencia suprarrenal.'
    },
    // Hematologia
    {
      id: 'hemato-1',
      name: 'Anemia Ferropénica',
      sistema: System.HEMATOLOGIA,
      etimologia: 'Del griego "an-" (sin) y "haima" (sangre). Disminución de glóbulos rojos por falta de hierro.',
      definicionClinica: 'Anemia microcítica e hipocrómica causada por una deficiencia de hierro, el componente esencial para la síntesis de la hemoglobina.',
      sintomatologia: ['Palidez', 'Astenia', 'Disnea de esfuerzo', 'Taquicardia', 'Coiloniquia (uñas en cuchara)', 'Pica'],
      diagnosticoNANDA: '[00092] Intolerancia a la actividad r/c desequilibrio entre el aporte y la demanda de oxígeno.',
      intervencionesNIC: ['[4030] Administración de productos sanguíneos', '[2304] Administración de medicación: oral', '[5270] Apoyo emocional'],
      resultadosNOC: ['[0405] Perfusión tisular: celular', '[0005] Tolerancia a la actividad', '[0002] Conservación de la energía'],
      planDeCuidados: 'Administración de suplementos de hierro (oral o IV). Educación sobre dieta rica en hierro y vitamina C. Monitorización de niveles de hemoglobina y ferritina. Identificar y tratar la causa de la pérdida de hierro (ej. sangrado digestivo).',
      farmacosPrincipales: ['Sulfato ferroso', 'Hierro sacarosa IV'],
      clavesResumen: 'Causa más común de anemia a nivel mundial. Analítica clave: Hb baja, VCM bajo, ferritina baja, transferrina alta. Investigar siempre la causa subyacente, especialmente en varones y mujeres postmenopáusicas.'
    },
    {
      id: 'hemato-2',
      name: 'Trombocitopenia',
      sistema: System.HEMATOLOGIA,
      etimologia: 'Del griego "thrombos" (coágulo), "kytos" (célula) y "penia" (deficiencia). Recuento de plaquetas por debajo de lo normal.',
      definicionClinica: 'Disminución del número de plaquetas (trombocitos) en la sangre por debajo de 150.000/μL. Puede ser causada por una menor producción en la médula ósea, un aumento de la destrucción o un secuestro esplénico.',
      sintomatologia: ['Petequias', 'Púrpura', 'Equimosis', 'Epistaxis', 'Gingivorragia', 'Sangrado menstrual abundante'],
      diagnosticoNANDA: '[00206] Riesgo de sangrado r/c disminución del recuento de plaquetas.',
      intervencionesNIC: ['[4010] Precauciones contra la hemorragia', '[6654] Vigilancia', '[2840] Administración de anestesia', '[4030] Administración de productos sanguíneos (plaquetas)'],
      resultadosNOC: ['[0413] Coagulación sanguínea', '[1902] Control del riesgo', '[0907] Integridad tisular: piel y membranas mucosas'],
      planDeCuidados: 'Monitorizar signos de sangrado (petequias, hematomas, sangrado de mucosas). Evitar procedimientos invasivos (inyecciones IM, sondajes). Utilizar cepillo de dientes suave y maquinilla eléctrica. Educar al paciente sobre signos de alarma y precauciones para evitar traumatismos.',
      farmacosPrincipales: ['Corticosteroides (Prednisona)', 'Inmunoglobulina intravenosa (IgIV)', 'Romiplostim', 'Eltrombopag'],
      clavesResumen: 'Riesgo principal: hemorragia. Recuento <50.000 aumenta riesgo con trauma, <10.000 riesgo de sangrado espontáneo. Es crucial identificar la causa (inmune, inducida por fármacos, infecciosa).'
    },
    {
      id: 'hemato-3',
      name: 'Leucemia Mieloide Aguda (LMA)',
      sistema: System.HEMATOLOGIA,
      etimologia: 'Del griego "leukos" (blanco) y "haima" (sangre). Cáncer de la línea mieloide de las células sanguíneas.',
      definicionClinica: 'Neoplasia maligna caracterizada por la proliferación rápida de células blásticas anormales de la serie mieloide en la médula ósea, que interfieren con la producción de células sanguíneas normales.',
      sintomatologia: ['Fatiga, debilidad (anemia)', 'Fiebre, infecciones recurrentes (neutropenia)', 'Sangrado fácil, petequias (trombocitopenia)', 'Dolor óseo', 'Hepatoesplenomegalia'],
      diagnosticoNANDA: '[00045] Riesgo de deterioro de la mucosa oral r/c efectos secundarios del tratamiento (quimioterapia).',
      intervencionesNIC: ['[6550] Protección contra las infecciones (aislamiento neutropénico)', '[1730] Restablecimiento de la salud bucal', '[4010] Precauciones contra la hemorragia', '[5270] Apoyo emocional'],
      resultadosNOC: ['[0703] Severidad de la infección', '[1100] Salud oral', '[1300] Aceptación: estado de salud'],
      planDeCuidados: 'Manejo en aislamiento protector si hay neutropenia severa. Administración de quimioterapia de inducción y consolidación. Soporte transfusional (concentrados de hematíes, plaquetas). Profilaxis y tratamiento de infecciones. Cuidado exhaustivo de la mucosa oral.',
      farmacosPrincipales: ['Citarabina', 'Daunorrubicina', 'Idarubicina', 'Antibióticos de amplio espectro'],
      clavesResumen: 'Leucemia aguda más común en adultos. Urgencia oncológica. Diagnóstico: aspirado de médula ósea con >20% de blastos. El tratamiento es intensivo y requiere hospitalización prolongada.'
    },
    {
      id: 'hemato-4',
      name: 'Linfoma de Hodgkin',
      sistema: System.HEMATOLOGIA,
      etimologia: 'Nombrado por Thomas Hodgkin. Cáncer del sistema linfático.',
      definicionClinica: 'Neoplasia maligna del sistema linfoide caracterizada por la presencia de células de Reed-Sternberg en un fondo celular inflamatorio. Típicamente se origina en un grupo ganglionar y se disemina de forma ordenada a otros grupos contiguos.',
      sintomatologia: ['Adenopatías indoloras (supraclaviculares, cervicales)', 'Fiebre, sudoración nocturna, pérdida de peso (>10% en 6 meses) - "Síntomas B"', 'Prurito', 'Dolor ganglionar con la ingesta de alcohol'],
      diagnosticoNANDA: '[00093] Fatiga r/c proceso de la enfermedad y efectos del tratamiento.',
      intervencionesNIC: ['[0180] Manejo de la energía', '[6610] Identificación de riesgos: infección', '[1450] Manejo de las náuseas', '[5270] Apoyo emocional'],
      resultadosNOC: ['[0007] Nivel de fatiga', '[1305] Adaptación psicosocial: cambio de vida', '[1618] Control de náuseas y vómitos'],
      planDeCuidados: 'Manejo de los efectos secundarios de la quimioterapia y radioterapia (náuseas, mucositis, fatiga). Monitorización y prevención de infecciones. Apoyo psicológico y educación sobre la enfermedad y el tratamiento. Vigilancia de toxicidades a largo plazo (cardíaca, pulmonar, segundas neoplasias).',
      farmacosPrincipales: ['Doxorrubicina', 'Bleomicina', 'Vinblastina', 'Dacarbazina (esquema ABVD)'],
      clavesResumen: 'Cáncer con alta tasa de curación. El diagnóstico se confirma con biopsia ganglionar (células de Reed-Sternberg). Dos picos de incidencia: adultos jóvenes (20-30 años) y mayores de 50.'
    },
    // Dermatologia
    {
      id: 'derma-1',
      name: 'Psoriasis',
      sistema: System.DERMATOLOGIA,
      etimologia: 'Del griego "psora" (picor). Enfermedad inflamatoria crónica de la piel.',
      definicionClinica: 'Enfermedad cutánea inflamatoria crónica, mediada por el sistema inmunitario, que causa una rápida acumulación de células en la superficie de la piel, formando placas escamosas y pruriginosas.',
      sintomatologia: ['Placas eritematosas bien delimitadas', 'Escamas plateadas', 'Prurito', 'Fenómeno de Koebner', 'Afectación ungueal (pitting)'],
      diagnosticoNANDA: '[00046] Deterioro de la integridad cutánea r/c proceso inflamatorio.',
      intervencionesNIC: ['[3590] Vigilancia de la piel', '[1660] Cuidado de los pies', '[5230] Mejorar el afrontamiento'],
      resultadosNOC: ['[1101] Integridad tisular: piel y membranas mucosas', '[2008] Estado de comodidad: físico', '[1302] Afrontamiento de problemas'],
      planDeCuidados: 'Aplicación de tratamientos tópicos (corticoides, análogos de vitamina D). Fototerapia. Educación sobre hidratación de la piel y evitar desencadenantes. Apoyo psicológico por el impacto en la autoimagen.',
      farmacosPrincipales: ['Betametasona (tópica)', 'Calcipotriol', 'Metotrexato', 'Adalimumab (biológico)'],
      clavesResumen: 'Enfermedad autoinmune, no contagiosa. Puede asociarse a artritis psoriásica y síndrome metabólico. El estrés es un desencadenante común.'
    },
    {
      id: 'derma-2',
      name: 'Melanoma Maligno',
      sistema: System.DERMATOLOGIA,
      etimologia: 'Del griego "melas" (negro) y "-oma" (tumor). Cáncer de piel derivado de los melanocitos.',
      definicionClinica: 'Neoplasia maligna de los melanocitos, las células productoras de pigmento. Es el cáncer de piel más agresivo por su alta capacidad de metástasis.',
      sintomatologia: ['Lesión pigmentada con asimetría, bordes irregulares, color variado, diámetro >6mm y evolución (ABCDE)', 'Sangrado o picor en un lunar preexistente'],
      diagnosticoNANDA: '[00047] Riesgo de deterioro de la integridad cutánea.',
      intervencionesNIC: ['[3590] Vigilancia de la piel', '[5510] Educación para la salud', '[5602] Enseñanza: proceso de la enfermedad'],
      resultadosNOC: ['[1101] Integridad tisular: piel y membranas mucosas', '[1603] Conducta de búsqueda de salud', '[1847] Conocimiento: manejo del cáncer'],
      planDeCuidados: 'Educación sobre autoexploración de la piel y fotoprotección. Preparación para la biopsia excisional. Apoyo emocional ante el diagnóstico. Cuidados de la herida quirúrgica.',
      farmacosPrincipales: ['Pembrolizumab (inmunoterapia)', 'Nivolumab', 'Dabrafenib/Trametinib (terapia dirigida)'],
      clavesResumen: 'El factor pronóstico más importante es el índice de Breslow (profundidad de la invasión). El diagnóstico precoz es fundamental. La regla del ABCDE es clave para la detección.'
    },
    {
      id: 'derma-3',
      name: 'Dermatitis Atópica (Eczema)',
      sistema: System.DERMATOLOGIA,
      etimologia: 'Del griego "derma" (piel), "-itis" (inflamación) y "atopia" (reacción de hipersensibilidad). Condición inflamatoria crónica de la piel.',
      definicionClinica: 'Enfermedad inflamatoria crónica y pruriginosa de la piel que cursa en brotes. Se asocia frecuentemente con una historia personal o familiar de asma, rinitis alérgica o alergias alimentarias.',
      sintomatologia: ['Prurito intenso', 'Piel seca (xerosis)', 'Lesiones eccematosas (eritema, vesículas, exudación)', 'Líneas de Dennie-Morgan (pliegues infraorbitarios)', 'Liquenificación (engrosamiento de la piel por rascado crónico)'],
      diagnosticoNANDA: '[00048] Deterioro de la integridad tisular r/c proceso inflamatorio y rascado.',
      intervencionesNIC: ['[3584] Cuidados de la piel: tratamiento tópico', '[1400] Manejo del dolor (prurito)', '[5602] Enseñanza: proceso de la enfermedad', '[5230] Mejorar el afrontamiento'],
      resultadosNOC: ['[1101] Integridad tisular: piel y membranas mucosas', '[1608] Control de síntomas', '[2101] Dolor: efectos nocivos'],
      planDeCuidados: 'Educación sobre hidratación intensiva y regular de la piel con emolientes. Aplicación de corticoides tópicos o inhibidores de la calcineurina durante los brotes. Identificar y evitar desencadenantes (alérgenos, irritantes). Manejo del prurito con antihistamínicos.',
      farmacosPrincipales: ['Hidrocortisona (tópica)', 'Tacrolimus (tópico)', 'Emolientes', 'Cetirizina', 'Dupilumab (biológico)'],
      clavesResumen: 'El prurito es el síntoma cardinal. El ciclo picor-rascado perpetúa la enfermedad. La base del tratamiento es la restauración de la barrera cutánea con hidratación. Común en la infancia, pero puede persistir en la edad adulta.'
    },
    {
      id: 'derma-4',
      name: 'Herpes Zóster',
      sistema: System.DERMATOLOGIA,
      etimologia: 'Del griego "herpein" (arrastrarse) y "zoster" (cinturón). Reactivación del virus varicela-zóster.',
      definicionClinica: 'Infección viral causada por la reactivación del virus de la varicela-zóster (VVZ), que permanece latente en los ganglios de la raíz dorsal. Se caracteriza por una erupción vesicular dolorosa unilateral que sigue el trayecto de un dermatoma.',
      sintomatologia: ['Dolor, ardor o parestesias en un dermatoma (prodromos)', 'Erupción de vesículas sobre base eritematosa', 'Distribución unilateral que no cruza la línea media', 'Fiebre, malestar general', 'Neuralgia postherpética (dolor persistente)'],
      diagnosticoNANDA: '[00132] Dolor agudo r/c inflamación de las terminaciones nerviosas por el virus.',
      intervencionesNIC: ['[1400] Manejo del dolor', '[3590] Vigilancia de la piel', '[6540] Control de infecciones', '[2300] Administración de medicación'],
      resultadosNOC: ['[1605] Control del dolor', '[2102] Nivel de dolor', '[1101] Integridad tisular: piel y membranas mucosas'],
      planDeCuidados: 'Administración precoz de antivirales. Manejo del dolor con analgésicos. Cuidados locales de las lesiones para prevenir sobreinfección. Aislar al paciente de personas inmunodeprimidas o no vacunadas contra la varicela. Educación sobre la neuralgia postherpética.',
      farmacosPrincipales: ['Aciclovir', 'Valaciclovir', 'Famciclovir', 'Gabapentina (para neuralgia)'],
      clavesResumen: 'El diagnóstico es clínico. El tratamiento antiviral precoz (<72h) reduce la severidad y duración de los síntomas y el riesgo de neuralgia postherpética. Es contagioso para quienes no han pasado la varicela.'
    },
    // Oncologicas
    {
      id: 'onco-1',
      name: 'Cáncer de Pulmón',
      sistema: System.ONCOLOGICAS,
      etimologia: 'Del latín "cancer" (cangrejo). Crecimiento celular maligno en los tejidos pulmonares.',
      definicionClinica: 'Neoplasia maligna originada en el epitelio bronquial o alveolar del pulmón. Se divide principalmente en cáncer de pulmón de células no pequeñas (CPCNP) y de células pequeñas (CPCP).',
      sintomatologia: ['Tos persistente', 'Hemoptisis', 'Dolor torácico', 'Disnea', 'Pérdida de peso', 'Afonía'],
      diagnosticoNANDA: '[00132] Dolor agudo r/c agentes lesivos (biológicos).',
      intervencionesNIC: ['[1400] Manejo del dolor', '[6654] Vigilancia', '[3320] Oxigenoterapia', '[5270] Apoyo emocional'],
      resultadosNOC: ['[1605] Control del dolor', '[2102] Nivel de dolor', '[1305] Adaptación psicosocial: cambio de vida'],
      planDeCuidados: 'Manejo del dolor y otros síntomas. Soporte respiratorio. Administración de quimioterapia/inmunoterapia. Cuidados del paciente con radioterapia. Apoyo nutricional. Acompañamiento emocional y familiar.',
      farmacosPrincipales: ['Cisplatino', 'Paclitaxel', 'Pembrolizumab', 'Osimertinib'],
      clavesResumen: 'Principal causa de muerte por cáncer en el mundo. Factor de riesgo más importante: tabaquismo. El CPCP es más agresivo y con diseminación temprana. El CPCNP tiene opciones de terapia dirigida según mutaciones.'
    },
    {
      id: 'onco-2',
      name: 'Cáncer de Mama',
      sistema: System.ONCOLOGICAS,
      etimologia: 'Tumor maligno que se origina en las células de la mama.',
      definicionClinica: 'Proliferación maligna de células epiteliales que revisten los conductos o lobulillos mamarios. Es el cáncer más frecuente en mujeres.',
      sintomatologia: ['Nódulo o masa palpable no dolorosa', 'Retracción del pezón', 'Cambios en la piel (piel de naranja)', 'Secreción por el pezón (sanguinolenta)', 'Adenopatía axilar'],
      diagnosticoNANDA: '[00126] Conocimientos deficientes sobre el autoexamen de mamas.',
      intervencionesNIC: ['[5606] Enseñanza: individual', '[5240] Asesoramiento', '[5440] Aumentar los sistemas de apoyo', '[6610] Identificación de riesgos'],
      resultadosNOC: ['[1854] Conocimiento: autoexamen de mamas', '[1302] Afrontamiento de problemas', '[1300] Aceptación: estado de salud'],
      planDeCuidados: 'Educación sobre autoexploración mamaria. Apoyo emocional pre y post diagnóstico. Manejo de efectos secundarios de quimio/radioterapia (náuseas, mucositis, fatiga). Cuidados del drenaje post-quirúrgico. Prevención y manejo del linfedema.',
      farmacosPrincipales: ['Tamoxifeno', 'Anastrozol', 'Trastuzumab', 'Paclitaxel', 'Doxorrubicina'],
      clavesResumen: 'La detección precoz (mamografía) mejora drásticamente el pronóstico. Clasificación molecular es clave para el tratamiento (receptores hormonales, HER2). La mayoría son hormonodependientes.'
    },
    {
      id: 'onco-3',
      name: 'Cáncer Colorrectal',
      sistema: System.ONCOLOGICAS,
      etimologia: 'Tumor maligno originado en la mucosa del colon o el recto.',
      definicionClinica: 'Neoplasia maligna que se desarrolla a partir de pólipos adenomatosos en el revestimiento interior del intestino grueso. Es uno de los cánceres más comunes en ambos sexos.',
      sintomatologia: ['Cambios en el hábito intestinal (diarrea/estreñimiento)', 'Rectorragia o hematoquecia', 'Dolor abdominal', 'Sensación de evacuación incompleta (tenesmo)', 'Anemia ferropénica inexplicada'],
      diagnosticoNANDA: '[00119] Afrontamiento ineficaz r/c diagnóstico de cáncer.',
      intervencionesNIC: ['[0460] Manejo de la diarrea', '[0450] Manejo del estreñimiento', '[1570] Manejo del vómito', '[4820] Cuidados de la ostomía', '[5270] Apoyo emocional'],
      resultadosNOC: ['[1302] Afrontamiento de problemas', '[2100] Nivel de comodidad', '[1629] Autocontrol: ostomía'],
      planDeCuidados: 'Preparación del paciente para la colonoscopia diagnóstica y la cirugía. Cuidados pre y postoperatorios, incluyendo el posible manejo de una ostomía. Administración de quimioterapia y manejo de sus efectos secundarios. Apoyo nutricional y emocional.',
      farmacosPrincipales: ['5-Fluorouracilo (5-FU)', 'Oxaliplatino', 'Irinotecan', 'Bevacizumab (anti-VEGF)', 'Cetuximab (anti-EGFR)'],
      clavesResumen: 'La mayoría se originan de pólipos adenomatosos, lo que hace crucial el cribado con colonoscopia a partir de los 45-50 años. El antígeno carcinoembrionario (CEA) es un marcador tumoral útil para el seguimiento, no para el diagnóstico.'
    },
    {
      id: 'onco-4',
      name: 'Cáncer de Próstata',
      sistema: System.ONCOLOGICAS,
      etimologia: 'Tumor maligno que se desarrolla en la próstata, una glándula del sistema reproductor masculino.',
      definicionClinica: 'Adenocarcinoma que se origina en las células epiteliales de la glándula prostática. Es uno de los cánceres más diagnosticados en hombres.',
      sintomatologia: ['Frecuentemente asintomático en fases iniciales', 'Dificultad para iniciar la micción', 'Flujo urinario débil o interrumpido', 'Polaquiuria, nicturia', 'Dolor óseo (en enfermedad metastásica)', 'Hematuria o hemospermia'],
      diagnosticoNANDA: '[00016] Deterioro de la eliminación urinaria r/c obstrucción uretral por el tumor.',
      intervencionesNIC: ['[0590] Manejo de la eliminación urinaria', '[5240] Asesoramiento', '[5610] Enseñanza: procedimiento/tratamiento', '[1400] Manejo del dolor'],
      resultadosNOC: ['[0503] Eliminación urinaria', '[1300] Aceptación: estado de salud', '[1605] Control del dolor'],
      planDeCuidados: 'Apoyo y educación sobre las opciones de tratamiento (cirugía, radioterapia, vigilancia activa, terapia hormonal). Manejo de los efectos secundarios del tratamiento (incontinencia urinaria, disfunción eréctil). Soporte emocional. Manejo del dolor en enfermedad avanzada.',
      farmacosPrincipales: ['Leuprorelina', 'Bicalutamida', 'Abiraterona', 'Enzalutamida', 'Docetaxel'],
      clavesResumen: 'El cribado se realiza con tacto rectal y determinación de PSA (Antígeno Prostático Específico). El PSA es sensible pero no específico. La mayoría son de crecimiento lento. El principal sitio de metástasis es el hueso.'
    },
    {
      id: 'onco-5',
      name: 'Cáncer Gástrico',
      sistema: System.ONCOLOGICAS,
      etimologia: 'Tumor maligno originado en la mucosa del estómago.',
      definicionClinica: 'Neoplasia maligna, predominantemente adenocarcinoma, que se desarrolla en el revestimiento del estómago. A menudo se diagnostica en estadios avanzados.',
      sintomatologia: ['Dispepsia, ardor', 'Saciedad precoz', 'Dolor epigástrico', 'Pérdida de peso, anorexia', 'Vómitos, disfagia', 'Melena o anemia ferropénica'],
      diagnosticoNANDA: '[00002] Desequilibrio nutricional: inferior a las necesidades corporales r/c saciedad precoz y anorexia.',
      intervencionesNIC: ['[1100] Manejo de la nutrición', '[1240] Ayuda para ganar peso', '[5270] Apoyo emocional', '[2380] Manejo de la medicación'],
      resultadosNOC: ['[1004] Estado nutricional', '[1008] Estado nutricional: ingestión alimentaria y de líquidos', '[1300] Aceptación: estado de salud'],
      planDeCuidados: 'Soporte nutricional (suplementos orales, nutrición enteral/parenteral). Cuidados pre y postoperatorios de la gastrectomía. Manejo de efectos secundarios de la quimioterapia. Control del dolor. Apoyo emocional.',
      farmacosPrincipales: ['5-Fluorouracilo', 'Cisplatino', 'Oxaliplatino', 'Trastuzumab (si es HER2+)'],
      clavesResumen: 'Principal factor de riesgo: infección por Helicobacter pylori. El diagnóstico se realiza por endoscopia con biopsia. Síntomas vagos y tardíos, por lo que el pronóstico suele ser malo. Ganglio de Virchow (supraclavicular izquierdo) es un signo clásico de metástasis.'
    },
    // Nefrologia / Urologia
    {
      id: 'nefro-1',
      name: 'Insuficiencia Renal Aguda (IRA)',
      sistema: System.NEFROLOGIA_UROLOGIA,
      etimologia: 'Del latín "insufficientia" (incapacidad) y "renalis" (relativo al riñón). Pérdida rápida de la función renal.',
      definicionClinica: 'Deterioro brusco de la función renal que resulta en la retención de productos nitrogenados (urea, creatinina) y la alteración del equilibrio hidroelectrolítico y ácido-base.',
      sintomatologia: ['Oliguria o anuria', 'Edema periférico', 'Fatiga', 'Náuseas', 'Confusión', 'Hiperpotasemia en ECG'],
      diagnosticoNANDA: '[00016] Deterioro de la eliminación urinaria r/c disfunción renal.',
      intervencionesNIC: ['[4120] Manejo de líquidos', '[2080] Manejo de líquidos y electrólitos', '[1876] Cuidados del catéter de diálisis'],
      resultadosNOC: ['[0601] Equilibrio hídrico', '[0600] Equilibrio electrolítico y ácido-base', '[0504] Función renal'],
      planDeCuidados: 'Identificar y tratar la causa (prerrenal, renal, postrenal). Monitorización estricta de diuresis, peso, balance hídrico y electrolitos (especialmente potasio). Ajuste de dosis de fármacos. Preparación para terapia de reemplazo renal si es necesario.',
      farmacosPrincipales: ['Furosemida (si no hay anuria)', 'Bicarbonato sódico (para acidosis)', 'Gluconato cálcico (para hiperpotasemia)'],
      clavesResumen: 'Clasificación por causa: prerrenal (hipoperfusión), renal (daño intrínseco) y postrenal (obstrucción). La creatinina es un marcador tardío. La diuresis es un signo vital renal. Urgencia: hiperpotasemia severa.'
    },
    {
      id: 'nefro-2',
      name: 'Infección del Tracto Urinario (ITU)',
      sistema: System.NEFROLOGIA_UROLOGIA,
      etimologia: 'Infección en cualquier parte del sistema urinario.',
      definicionClinica: 'Presencia de microorganismos patógenos en el tracto urinario, con o sin presencia de síntomas. Puede ser baja (cistitis) o alta (pielonefritis).',
      sintomatologia: ['Disuria (dolor al orinar)', 'Polaquiuria (aumento de frecuencia)', 'Tenesmo vesical', 'Orina turbia o maloliente', 'Fiebre y dolor lumbar (en pielonefritis)'],
      diagnosticoNANDA: '[00016] Deterioro de la eliminación urinaria r/c irritación de la mucosa vesical.',
      intervencionesNIC: ['[0590] Manejo de la eliminación urinaria', '[1400] Manejo del dolor', '[6540] Control de infecciones', '[5616] Enseñanza: medicamentos prescritos'],
      resultadosNOC: ['[0503] Eliminación urinaria', '[2102] Nivel de dolor', '[1608] Control de síntomas'],
      planDeCuidados: 'Administración de antibióticos según pauta. Fomentar la ingesta de líquidos. Administración de analgésicos para la disuria. Educación sobre medidas higiénicas para prevenir recurrencias.',
      farmacosPrincipales: ['Fosfomicina', 'Nitrofurantoína', 'Ciprofloxacino', 'Ceftriaxona (en pielonefritis)'],
      clavesResumen: 'Mucho más frecuente en mujeres. Agente causal más común: Escherichia coli. La ITU alta (pielonefritis) es una infección grave que puede llevar a sepsis. Un urocultivo confirma el diagnóstico y guía el tratamiento antibiótico.'
    },
    {
      id: 'nefro-3',
      name: 'Litiasis Renal (Cálculos Renales)',
      sistema: System.NEFROLOGIA_UROLOGIA,
      etimologia: 'Del griego "lithos" (piedra). Formación de cálculos en el riñón o vías urinarias.',
      definicionClinica: 'Presencia de concreciones sólidas (cálculos) formadas por la cristalización de sales minerales en el riñón o en cualquier punto del tracto urinario.',
      sintomatologia: ['Dolor lumbar intenso y agudo (cólico nefrítico)', 'Irradiación del dolor a flanco e ingle', 'Hematuria', 'Náuseas y vómitos', 'Polaquiuria y disuria'],
      diagnosticoNANDA: '[00132] Dolor agudo r/c obstrucción y espasmo del uréter.',
      intervencionesNIC: ['[1400] Manejo del dolor', '[4120] Manejo de líquidos', '[0450] Manejo del estreñimiento', '[2300] Administración de medicación'],
      resultadosNOC: ['[1605] Control del dolor', '[2102] Nivel de dolor', '[0503] Eliminación urinaria'],
      planDeCuidados: 'Manejo intensivo del dolor con AINEs y/o opiáceos. Fomentar alta ingesta de líquidos para facilitar la expulsión. Filtrar la orina para recoger el cálculo y analizarlo. Educación sobre dieta para prevenir recurrencias según la composición del cálculo.',
      farmacosPrincipales: ['Dexketoprofeno', 'Metamizol', 'Morfina', 'Tamsulosina (facilita expulsión)'],
      clavesResumen: 'El síntoma principal es el cólico nefrítico, uno de los dolores más intensos. La mayoría de los cálculos se expulsan espontáneamente. El tipo más común es de oxalato cálcico. La prueba de imagen de elección es el TAC sin contraste.'
    },
    // Musculoesqueletico
    {
      id: 'musculo-1',
      name: 'Artritis Reumatoide',
      sistema: System.MUSCULOESQUELETICO,
      etimologia: 'Del griego "arthron" (articulación) e "-itis" (inflamación). Enfermedad autoinmune articular.',
      definicionClinica: 'Enfermedad inflamatoria crónica, sistémica y autoinmune, que afecta principalmente a las articulaciones sinoviales, causando una poliartritis simétrica y erosiva que puede llevar a una deformidad y discapacidad progresiva.',
      sintomatologia: ['Dolor e inflamación en articulaciones (manos, muñecas, pies)', 'Rigidez matutina prolongada (>1 hora)', 'Simetría de la afectación articular', 'Fatiga, febrícula', 'Nódulos reumatoides'],
      diagnosticoNANDA: '[00133] Dolor crónico r/c proceso inflamatorio articular.',
      intervencionesNIC: ['[1410] Manejo del dolor: crónico', '[0224] Terapia de ejercicios: movilidad articular', '[0180] Manejo de la energía', '[5616] Enseñanza: medicamentos prescritos'],
      resultadosNOC: ['[2101] Dolor: efectos nocivos', '[0208] Movilidad', '[0300] Autocuidados: AVD'],
      planDeCuidados: 'Manejo del dolor y la inflamación. Administración de FAMEs (fármacos antirreumáticos modificadores de la enfermedad). Terapia física y ocupacional para mantener la función articular. Educación sobre protección articular y conservación de energía. Apoyo emocional.',
      farmacosPrincipales: ['Metotrexato', 'Prednisona', 'Adalimumab (biológico)', 'Etanercept'],
      clavesResumen: 'Afecta más a mujeres. El tratamiento precoz con FAMEs es clave para prevenir el daño articular irreversible. El Factor Reumatoide y los anticuerpos anti-CCP son marcadores diagnósticos importantes.'
    },
    {
      id: 'musculo-2',
      name: 'Osteoporosis',
      sistema: System.MUSCULOESQUELETICO,
      etimologia: 'Del griego "osteon" (hueso) y "poros" (poro). Hueso poroso.',
      definicionClinica: 'Enfermedad esquelética sistémica caracterizada por una baja masa ósea y un deterioro de la microarquitectura del tejido óseo, que conduce a un aumento de la fragilidad ósea y, en consecuencia, a un mayor riesgo de fracturas.',
      sintomatologia: ['Generalmente asintomática hasta que ocurre una fractura', 'Fracturas por fragilidad (cadera, vértebras, muñeca)', 'Pérdida de estatura', 'Cifosis dorsal progresiva ("joroba de viuda")'],
      diagnosticoNANDA: '[00155] Riesgo de caídas r/c disminución de la densidad ósea y debilidad.',
      intervencionesNIC: ['[6490] Prevención de caídas', '[1100] Manejo de la nutrición', '[0200] Fomento del ejercicio', '[5612] Enseñanza: actividad/ejercicio prescrito'],
      resultadosNOC: ['[1909] Conducta de prevención de caídas', '[1004] Estado nutricional', '[1911] Conducta de seguridad personal'],
      planDeCuidados: 'Educación sobre prevención de caídas. Fomentar una dieta rica en calcio y vitamina D. Promover el ejercicio de carga (caminar) y de resistencia para fortalecer huesos y músculos. Administración de suplementos y fármacos antirresortivos.',
      farmacosPrincipales: ['Calcio', 'Vitamina D', 'Alendronato', 'Denosumab', 'Teriparatida'],
      clavesResumen: 'Enfermedad "silenciosa". Principalmente afecta a mujeres postmenopáusicas. El diagnóstico se realiza con densitometría ósea (DEXA). El objetivo del tratamiento es prevenir las fracturas.'
    },
    // Ginecologia y Obstetricia
    {
      id: 'gine-1',
      name: 'Preeclampsia',
      sistema: System.GINECOLOGIA_OBSTETRICIA,
      etimologia: 'Del griego "pre-" (antes) y "eklampsis" (destello). Complicación grave del embarazo.',
      definicionClinica: 'Trastorno multisistémico propio del embarazo que se define por la aparición de hipertensión arterial (≥140/90 mmHg) y proteinuria después de las 20 semanas de gestación en una mujer previamente normotensa.',
      sintomatologia: ['Hipertensión', 'Proteinuria', 'Edema facial y de manos', 'Cefalea intensa', 'Alteraciones visuales (escotomas, fotopsias)', 'Dolor epigástrico (epigastralgia)'],
      diagnosticoNANDA: '[00208] Riesgo de disminución de la perfusión tisular materno-fetal r/c vasoespasmo.',
      intervencionesNIC: ['[6772] Monitorización fetal electrónica: durante el parto', '[6950] Cuidados de la embarazada de alto riesgo', '[4150] Regulación hemodinámica', '[2620] Monitorización neurológica'],
      resultadosNOC: ['[2511] Severidad de la preeclampsia', '[0111] Estado fetal: anteparto', '[0802] Signos vitales'],
      planDeCuidados: 'Monitorización estricta de la tensión arterial materna y del bienestar fetal. Control de diuresis y balance hídrico. Administración de antihipertensivos. Administración de sulfato de magnesio para prevenir convulsiones (eclampsia). Preparación para la finalización de la gestación.',
      farmacosPrincipales: ['Labetalol', 'Nifedipino', 'Sulfato de magnesio', 'Corticoides (para maduración pulmonar fetal)'],
      clavesResumen: 'Urgencia obstétrica. El único tratamiento curativo es el parto. El sulfato de magnesio es el fármaco de elección para la profilaxis y tratamiento de las convulsiones eclámpticas. Puede evolucionar al síndrome HELLP.'
    },
    {
      id: 'gine-2',
      name: 'Embarazo Ectópico',
      sistema: System.GINECOLOGIA_OBSTETRICIA,
      etimologia: 'Del griego "ek" (fuera) y "topos" (lugar). Embarazo fuera del útero.',
      definicionClinica: 'Implantación del blastocisto fuera de la cavidad endometrial. La localización más frecuente es la trompa de Falopio (95%).',
      sintomatologia: ['Amenorrea', 'Dolor abdominal unilateral agudo', 'Sangrado vaginal anormal', 'Signos de shock hipovolémico (si hay rotura tubárica): hipotensión, taquicardia, síncope'],
      diagnosticoNANDA: '[00132] Dolor agudo r/c distensión o rotura de la trompa de Falopio.',
      intervencionesNIC: ['[4250] Manejo del shock: volumen', '[1400] Manejo del dolor', '[5270] Apoyo emocional', '[5240] Asesoramiento'],
      resultadosNOC: ['[0602] Hidratación', '[1605] Control del dolor', '[1302] Afrontamiento de problemas'],
      planDeCuidados: 'Monitorización hemodinámica. Administración de fluidoterapia y hemoderivados si hay shock. Manejo del dolor. Administración de Metotrexato en casos seleccionados o preparación para cirugía urgente (salpingectomía). Apoyo emocional por la pérdida gestacional.',
      farmacosPrincipales: ['Metotrexato', 'Suero salino fisiológico', 'Morfina', 'Inmunoglobulina Anti-D (si la madre es Rh-)'],
      clavesResumen: 'Emergencia ginecológica potencialmente mortal si se rompe. Diagnóstico: ecografía transvaginal (útero vacío) + niveles de β-hCG que no se duplican adecuadamente. Sospechar en toda mujer en edad fértil con dolor abdominal y/o sangrado.'
    },
    // Psiquiatria / Salud Mental
    {
      id: 'psiq-1',
      name: 'Trastorno Depresivo Mayor',
      sistema: System.PSIQUIATRIA_SALUD_MENTAL,
      etimologia: 'Del latín "depressio" (hundimiento). Trastorno del estado de ánimo caracterizado por una tristeza persistente.',
      definicionClinica: 'Trastorno del estado de ánimo que se caracteriza por la presencia de uno o más episodios depresivos mayores, definidos por un período de al menos dos semanas con un estado de ánimo deprimido o una pérdida de interés o placer (anhedonia) en casi todas las actividades.',
      sintomatologia: ['Ánimo deprimido', 'Anhedonia', 'Alteraciones del peso o apetito', 'Insomnio o hipersomnia', 'Agitación o enlentecimiento psicomotor', 'Fatiga, ideación suicida'],
      diagnosticoNANDA: '[00140] Riesgo de violencia autodirigida r/c desesperanza e ideación suicida.',
      intervencionesNIC: ['[6340] Prevención del suicidio', '[5330] Control del humor', '[4360] Modificación de la conducta', '[5270] Apoyo emocional'],
      resultadosNOC: ['[1408] Autocontrol de los impulsos suicidas', '[1402] Autocontrol de la ansiedad', '[1204] Equilibrio del estado de ánimo'],
      planDeCuidados: 'Valoración continua del riesgo de suicidio. Proporcionar un entorno seguro. Fomentar la expresión de sentimientos. Administrar medicación antidepresiva y educar sobre su latencia de efecto. Promover la participación en terapia y actividades gratificantes.',
      farmacosPrincipales: ['Sertralina', 'Escitalopram', 'Venlafaxina', 'Mirtazapina'],
      clavesResumen: 'El riesgo de suicidio es la principal preocupación. El tratamiento combina farmacoterapia (ISRS como primera línea) y psicoterapia. La mejoría con antidepresivos puede tardar de 4 a 6 semanas en ser evidente.'
    },
    {
      id: 'psiq-2',
      name: 'Trastorno de Ansiedad Generalizada (TAG)',
      sistema: System.PSIQUIATRIA_SALUD_MENTAL,
      etimologia: 'Del latín "anxietas" (angustia). Preocupación excesiva y persistente.',
      definicionClinica: 'Trastorno de ansiedad caracterizado por una preocupación y ansiedad excesivas y persistentes sobre diversos acontecimientos o actividades, que el individuo encuentra difícil de controlar y que se acompaña de síntomas somáticos.',
      sintomatologia: ['Preocupación incontrolable', 'Inquietud o nerviosismo', 'Fatigabilidad fácil', 'Dificultad para concentrarse', 'Irritabilidad', 'Tensión muscular, alteraciones del sueño'],
      diagnosticoNANDA: '[00146] Ansiedad r/c amenazas percibidas y estrés persistente.',
      intervencionesNIC: ['[5820] Disminución de la ansiedad', '[4920] Escucha activa', '[6000] Terapia de relajación', '[5230] Mejorar el afrontamiento'],
      resultadosNOC: ['[1211] Nivel de ansiedad', '[1302] Afrontamiento de problemas', '[1402] Autocontrol de la ansiedad'],
      planDeCuidados: 'Enseñar y practicar técnicas de relajación (respiración diafragmática, relajación muscular progresiva). Ayudar al paciente a identificar pensamientos distorsionados. Administrar medicación (ISRS, benzodiacepinas a corto plazo). Fomentar el ejercicio físico regular y la higiene del sueño.',
      farmacosPrincipales: ['Escitalopram', 'Paroxetina', 'Pregabalina', 'Lorazepam (corto plazo)'],
      clavesResumen: 'La clave es la preocupación crónica y generalizada, no asociada a un objeto o situación específica como en las fobias. El tratamiento de elección a largo plazo son los ISRS/IRSN y la terapia cognitivo-conductual (TCC).'
    },
    // Varios / Urgencias
    {
      id: 'varios-1',
      name: 'Sepsis',
      sistema: System.VARIOS,
      etimologia: 'Del griego "sepsis" (putrefacción). Respuesta sistémica y desregulada del cuerpo a una infección.',
      definicionClinica: 'Disfunción orgánica potencialmente mortal causada por una respuesta desregulada del huésped a la infección. El shock séptico es un subconjunto de la sepsis con anomalías circulatorias y metabólicas profundas.',
      sintomatologia: ['Fiebre o hipotermia', 'Taquicardia', 'Taquipnea', 'Alteración del estado mental', 'Hipotensión', 'Oliguria'],
      diagnosticoNANDA: '[00005] Riesgo de desequilibrio de la temperatura corporal.',
      intervencionesNIC: ['[4120] Manejo de líquidos y electrólitos', '[6540] Control de infecciones', '[2300] Administración de medicación', '[6680] Monitorización de signos vitales'],
      resultadosNOC: ['[0413] Perfusión tisular: periférica', '[0601] Equilibrio hídrico', '[0703] Severidad de la infección'],
      planDeCuidados: 'Inicio rápido de la "Hora de Oro": hemocultivos, lactato, administración de antibióticos de amplio espectro y fluidoterapia agresiva. Soporte de órganos (vasopresores, ventilación mecánica, terapia renal). Control estricto de glucemia.',
      farmacosPrincipales: ['Piperacilina-tazobactam', 'Vancomicina', 'Noradrenalina', 'Hidrocortisona (en shock refractario)'],
      clavesResumen: 'Urgencia médica. La detección precoz es clave. Usar escalas como qSOFA (quick SOFA) para el cribado. El lactato sérico es un marcador de hipoperfusión tisular.'
    },
    {
      id: 'varios-2',
      name: 'Tromboembolismo Pulmonar (TEP)',
      sistema: System.VARIOS,
      etimologia: 'Obstrucción de arterias pulmonares por un coágulo (trombo) desprendido (émbolo), usualmente de venas de las piernas.',
      definicionClinica: 'Oclusión o taponamiento de una parte del territorio arterial pulmonar a causa de un émbolo o trombo que procede de otra parte del cuerpo.',
      sintomatologia: ['Disnea de aparición súbita', 'Dolor torácico pleurítico', 'Taquipnea', 'Taquicardia', 'Hemoptisis', 'Síncope'],
      diagnosticoNANDA: '[00030] Deterioro del intercambio de gases r/c desequilibrio ventilación/perfusión.',
      intervencionesNIC: ['[3350] Monitorización respiratoria', '[3140] Manejo de las vías aéreas', '[4110] Precauciones contra el embolismo', '[2080] Manejo de líquidos y electrólitos'],
      resultadosNOC: ['[0402] Estado respiratorio: intercambio gaseoso', '[0415] Estado respiratorio', '[0421] Perfusión tisular: pulmonar'],
      planDeCuidados: 'Oxigenoterapia para mantener SaO2 >90%. Anticoagulación inmediata con heparina. Monitorización hemodinámica. Terapia trombolítica o embolectomía en TEP masivo con inestabilidad.',
      farmacosPrincipales: ['Heparina de bajo peso molecular (Enoxaparina)', 'Heparina no fraccionada', 'Alteplasa (trombolítico)', 'Apixabán (anticoagulación a largo plazo)'],
      clavesResumen: 'Urgencia médica potencialmente mortal. Sospecha alta en pacientes con TVP, cirugía reciente, inmovilización o cáncer. Diagnóstico clave: Angio-TC pulmonar. Dímero-D elevado es sensible pero poco específico.'
    },
    {
      id: 'varios-4',
      name: 'Shock Anafiláctico',
      sistema: System.VARIOS,
      etimologia: 'Del griego "ana-" (contra) y "phylaxis" (protección). Reacción alérgica grave y potencialmente mortal.',
      definicionClinica: 'Reacción de hipersensibilidad sistémica, de instauración rápida y potencialmente mortal, que cursa con compromiso respiratorio y/o circulatorio.',
      sintomatologia: ['Urticaria, angioedema', 'Dificultad respiratoria, estridor, sibilancias', 'Hipotensión, taquicardia', 'Dolor abdominal, vómitos', 'Sensación de muerte inminente'],
      diagnosticoNANDA: '[00032] Patrón respiratorio ineficaz r/c edema laríngeo y broncoespasmo.',
      intervencionesNIC: ['[6412] Manejo de la anafilaxia', '[3320] Oxigenoterapia', '[4250] Manejo del shock', '[2313] Administración de medicación: intramuscular'],
      resultadosNOC: ['[0410] Estado respiratorio: permeabilidad de las vías respiratorias', '[0401] Estado circulatorio', '[2105] Respuesta alérgica: sistémica'],
      planDeCuidados: 'Administración inmediata de adrenalina intramuscular. Mantener vía aérea permeable, administrar oxígeno a alto flujo. Colocar al paciente en posición de Trendelenburg si hay hipotensión. Fluidoterapia IV. Administrar antihistamínicos y corticoides como segunda línea.',
      farmacosPrincipales: ['Adrenalina (Epinefrina)', 'Salbutamol (nebulizado)', 'Clorfenamina', 'Hidrocortisona'],
      clavesResumen: 'Actuación inmediata es vital. La adrenalina es el único tratamiento de primera línea que salva la vida. Identificar y evitar el alérgeno es la clave de la prevención. Educar al paciente en el uso del autoinyector de adrenalina.'
    },
    {
      id: 'varios-8',
      name: 'VIH/SIDA',
      sistema: System.VARIOS,
      etimologia: 'Virus de Inmunodeficiencia Humana / Síndrome de Inmunodeficiencia Adquirida.',
      definicionClinica: 'Infección por el retrovirus VIH que ataca y destruye los linfocitos T CD4, debilitando progresivamente el sistema inmunitario. El SIDA es la fase más avanzada de la infección, definida por un recuento de CD4 <200 células/μL o la presencia de enfermedades oportunistas.',
      sintomatologia: ['Primoinfección: síndrome mononucleósido (fiebre, faringitis, adenopatías)', 'Fase crónica: asintomática', 'Fase SIDA: infecciones oportunistas (neumonía por P. jirovecii, toxoplasmosis cerebral), neoplasias (Sarcoma de Kaposi, linfoma)'],
      diagnosticoNANDA: '[00120] Baja autoestima situacional r/c estigma social y diagnóstico de enfermedad crónica.',
      intervencionesNIC: ['[6550] Protección contra las infecciones', '[5616] Enseñanza: medicamentos prescritos', '[5400] Potenciación de la autoestima', '[5240] Asesoramiento'],
      resultadosNOC: ['[1300] Aceptación: estado de salud', '[1623] Conducta de cumplimiento: medicación', '[1837] Conocimiento: control de la enfermedad'],
      planDeCuidados: 'Educación sobre la adherencia estricta al tratamiento antirretroviral (TARGA). Prevención y detección precoz de infecciones oportunistas. Apoyo psicológico y lucha contra el estigma. Promoción de prácticas sexuales seguras y reducción de daños.',
      farmacosPrincipales: ['Tenofovir', 'Emtricitabina', 'Dolutegravir', 'Darunavir/cobicistat'],
      clavesResumen: 'Enfermedad crónica manejable con tratamiento. El objetivo del TARGA es suprimir la carga viral hasta niveles indetectables ("Indetectable = Intransmisible"). El seguimiento se realiza con recuento de CD4 y carga viral.'
    },
    {
      id: 'varios-9',
      name: 'Quemaduras Graves',
      sistema: System.VARIOS,
      etimologia: 'Lesión en la piel u otros tejidos orgánicos causada principalmente por el calor o la radiación, la radiactividad, la electricidad, la fricción o el contacto con productos químicos.',
      definicionClinica: 'Lesión tisular por agentes térmicos, químicos, eléctricos o radiantes que compromete la integridad de la piel y puede afectar tejidos profundos, provocando una intensa respuesta inflamatoria sistémica y riesgo vital.',
      sintomatologia: ['Lesiones cutáneas (eritema, flictenas, escara)', 'Dolor intenso (en quemaduras de 1er y 2º grado)', 'Signos de shock hipovolémico (pérdida de plasma)', 'Signos de lesión de la vía aérea (esputo carbonáceo, disfonía, estridor)'],
      diagnosticoNANDA: '[00028] Riesgo de déficit de volumen de líquidos r/c pérdida de la barrera cutánea y extravasación de plasma.',
      intervencionesNIC: ['[3582] Cuidados de la piel: quemaduras', '[2080] Manejo de líquidos y electrólitos', '[3140] Manejo de las vías aéreas', '[1400] Manejo del dolor'],
      resultadosNOC: ['[0601] Equilibrio hídrico', '[1103] Curación de la herida: por segunda intención', '[1605] Control del dolor'],
      planDeCuidados: 'Asegurar vía aérea (especialmente en quemaduras faciales o por inhalación). Fluidoterapia intensiva con la fórmula de Parkland. Manejo del dolor con opiáceos IV. Cuidados de las heridas con curas estériles. Prevención de hipotermia e infecciones. Soporte nutricional hipercalórico e hiperproteico.',
      farmacosPrincipales: ['Suero Ringer Lactato', 'Morfina IV', 'Sulfadiazina argéntica (tópica)', 'Profilaxis antitetánica'],
      clavesResumen: 'Emergencia médica. La prioridad es ABC (Airway, Breathing, Circulation). El cálculo de la superficie corporal quemada (Regla de los 9) es crucial para la fluidoterapia. El shock por quemadura es la principal causa de muerte en las primeras horas.'
    }
];

export const GLOSSARY: { term: string; definition: string }[] = [
    { term: 'PAE', definition: 'Proceso de Atención de Enfermería. Método sistemático para brindar cuidados humanistas eficientes centrados en el logro de resultados esperados.' },
    { term: 'NANDA', definition: 'North American Nursing Diagnosis Association. Proporciona una clasificación estandarizada de los diagnósticos de enfermería.' },
    { term: 'NIC', definition: 'Nursing Interventions Classification. Clasificación normalizada de las intervenciones que realizan los profesionales de enfermería.' },
    { term: 'NOC', definition: 'Nursing Outcomes Classification. Clasificación normalizada de los resultados de los pacientes que se utilizan para evaluar el efecto de las intervenciones de enfermería.' },
    { term: 'Disnea', definition: 'Dificultad para respirar o sensación de falta de aire.' },
    { term: 'Diaforesis', definition: 'Sudoración profusa.' },
    { term: 'Hemoptisis', definition: 'Expectoración de sangre proveniente de los pulmones o los bronquios.' },
    { term: 'Oliguria', definition: 'Disminución de la producción de orina.' },
    { term: 'Isquemia', definition: 'Estrés celular causado por la disminución transitoria o permanente del flujo sanguíneo en el tejido.' },
];

export const RED_FLAGS: {title: string; content: string}[] = [
    { title: 'Dolor torácico súbito', content: 'Puede indicar IAM o TEP. Actuar de inmediato.' },
    { title: 'Alteración del nivel de conciencia', content: 'Signo de hipoxia, ACV o sepsis. Valoración neurológica urgente.' },
    { title: 'Dificultad respiratoria aguda', content: 'Riesgo de fallo respiratorio. Asegurar vía aérea y oxigenación.' },
];

export const URGENCY_30S: {title: string; content: string}[] = [
    { title: 'Parada cardiorrespiratoria (PCR)', content: 'Iniciar RCP. 30 compresiones : 2 ventilaciones. Usar DESA.' },
    { title: 'Shock anafiláctico', content: 'Adrenalina IM. Asegurar vía aérea. Oxígeno.' },
    { title: 'Hipoglucemia severa', content: 'Glucagón IM o Glucosa IV. No dar nada por boca si hay alteración de conciencia.' },
];
